# Generated by Django 3.2.7 on 2021-10-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('detalle_cargo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('id_caso', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion_caso', models.CharField(max_length=500)),
                ('video', models.CharField(blank=True, max_length=1, null=True)),
                ('audio', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'casos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionCaso',
            fields=[
                ('id_evcaso', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField()),
                ('fecha_realizacion', models.DateField()),
            ],
            options={
                'db_table': 'evaluacion_caso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluado',
            fields=[
                ('id_evaluado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=50)),
                ('video_respuesta', models.CharField(blank=True, max_length=1, null=True)),
                ('audio_respuesta', models.CharField(blank=True, max_length=1, null=True)),
                ('email', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'evaluado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id_evaluador', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'evaluador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=40)),
                ('apellido_p', models.CharField(max_length=20)),
                ('apellido_m', models.CharField(max_length=20)),
                ('num_cel', models.BigIntegerField()),
                ('email_personal', models.CharField(max_length=25)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_nac', models.DateField()),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_revision', models.DateField()),
            ],
            options={
                'db_table': 'resultado',
                'managed': False,
            },
        ),
    ]
